imports:
    - { resource: "@SetonoSyliusGiftCardPlugin/config/grids/setono_sylius_gift_card_admin_gift_card.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/config/grids/setono_sylius_gift_card_admin_gift_card_configuration.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/config/grids/setono_sylius_gift_card_admin_gift_card_order.yaml" }
    - { resource: "@SetonoSyliusGiftCardPlugin/config/grids/setono_sylius_gift_card_shop_gift_card.yaml" }

sylius_grid:
    templates:
        action:
            gift_card_create: "@SetonoSyliusGiftCardPlugin/admin/gift_card/Grid/Action/create.html.twig"
            gift_card_delete_conditional: "@SetonoSyliusGiftCardPlugin/admin/gift_card/Grid/Action/delete_conditional.html.twig"
            gift_card_balance: "@SetonoSyliusGiftCardPlugin/admin/gift_card/Grid/Action/gift_card_balance.html.twig"
            gift_card_list_conditional: "@SetonoSyliusGiftCardPlugin/admin/gift_card/Grid/Action/list_conditional.html.twig"
            gift_card_resend_email: '@SetonoSyliusGiftCardPlugin/admin/gift_card/Grid/Action/resend_email.html.twig'
